app:
  host: 0.0.0.0
  port: 9999
  base_url: http://127.0.0.1
db:
  user: postgres
  password: 'postgres'
  host: localhost
  port: 54321
  dbname: zero2prod

email:
  base_url: "localhost"
  sender_email: "test@gmail.com"